Tomadoc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    
    path('diagnose/',include('diagnose.urls')),
   # path('accounts', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'), name='password_reset_complete'), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views

from . import views
app_name='accounts'
urlpatterns = [
    path('',views.home,name="home"),
    path('accounts/login/',views.login_view,name='logIn'),
    path('accounts/register/',views.register_view,name='register'),
   path('accounts/logout/',views.logout_view,name='logout'),

   # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html'), name='password_reset'),
   # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'), name='password_reset_complete'),      
    ]

diagnose/urls.py
from django.urls import path,include
from . import views
app_name='diagnose'
urlpatterns = [
    path('upload/',views.upload.as_view(),name="upload"),
    path('predictions/',views.predictions.as_view(),name="predictions"),
    path('predictions/<int:id>/',views.delete_prediction.as_view(),name="delete_prediction"),
     path('pestidide/<int:id>/',views.delete_review.as_view(),name="delete_review"),
    #path('predictions/filtered',views.filter_predictions,name="filter_predictions"),
    path('prediction/<int:pk>/',views.prediction.as_view(),name="prediction"),
    path('pestiside/<int:pk>/<int:di>',views.Pestisides.as_view(),name="pestiside"),
    path('pestiside/review/<int:pk>/<int:di>',views.CommentView.as_view(),name="comment"),
    path('review/',views.review.as_view(),name="review"),
     path('profile/',views.upload_profile.as_view(),name="profile"),
     path('viewprofile/',views.view_profile.as_view(),name="view_profile"),
     path('dashboard/viewprofile/<int:id>/',views.view_dashprofile.as_view(),name="view_dashprofile"),
      path('dashboard/users',views.View_usersa.as_view(),name="dashusersa"),
      path('dashboard/diseases',views.View_Diseases.as_view(),name="dashdiseases"),
      path('dashboard/pestisides',views.View_Pestisides.as_view(),name="dashpestisides"),
      path('add_pestiside/',views.AddPestiside.as_view(),name="add_pestiside"),
       path('pestiside/<int:id>/',views.delete_pestiside.as_view(),name="delete_pestiside"),
       path('pestiside_update/<int:id>/',views.update_pestiside.as_view(),name="update_pestiside"),
       path('pestiside_details/<int:id>/',views.pestiside_details.as_view(),name="pestiside_details"),
       path('edit/<int:id>/',views.editDisease.as_view(),name="editDisease"),
   ]

diagnose/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
DISEASE_CHOICES = (('all','all'),
    ('Tomato mossaic virus','Tomato mossaic virus'),
    ('Tomato yellow leaf curl virus', 'Tomato yellow leaf curl virus'),
    ('Tomato target spot', 'Tomato target spot'),
    ('Tomato spider mites', 'Tomato spider mites'),
     ('Tomato septoira leaf spot', 'Tomato septoira leaf spot'),
      ('Tomato leaf mold', 'Tomato leaf mold'),
       ('Tomato late blight', 'Tomato late blight'),
       ('Tomato early blight', 'Tomato early blight'),
       ('Tomato bacterial spot', 'Tomato bacterial spot'))
class imageForm(forms.ModelForm):
         
    class Meta:
        model = ImageModel
        fields = ('imagefile',)
        
class ReviewForm(forms.ModelForm):
    class Meta:
        model=Review
        fields=('comment',)
        
class userdetailsForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','email',)
            
                        
class profileForm(forms.ModelForm):
	class Meta:
	    model = Profile
	    fields = ('imagefile',)  


class pestisideForm(forms.ModelForm):
    choices = forms.ModelChoiceField(queryset=Disease.objects.all())
    class Meta:
        model = Pestiside
        fields = ('name','imagefile','directions','price')
        

class FilterForm(forms.Form):
    #selectedplant = forms.ModelChoiceField(queryset=Disease.objects.all(), required=True)
    selected= forms.CharField(label='Filter by disease', widget=forms.Select(choices=DISEASE_CHOICES))

class diseaseForm(forms.ModelForm):
    model=Disease
    fields=('symptoms',)

    

diagnose/views.py
from django.shortcuts import render,redirect
from django.core.files.storage import FileSystemStorage
from django.urls import reverse
from django.views.generic.edit import DeleteView,FormView
from django.views.generic import ListView
from django.views import View
from django.shortcuts import get_object_or_404
from .forms import *
from .models import *
from .py_templates.my_model import *
from django.db.models import Count
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
# Create your views here.

#@method_decorator(login_required, name='dispatch')
class upload(LoginRequiredMixin,View):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    def get(self,request):
        prediction=None
        image=None
        form=imageForm()
        pestisides=None
        disease=None
        
        context={'form':form,'image':image,'disease':disease,'pestisides':pestisides}
        return render(request,'diagnose/predict.html',context)
    def post(self,request):
        user = User.objects.get(username=request.user)

        if request.method == 'POST':
            form=imageForm(request.POST,request.FILES)
            if form.is_valid():
               form.save()
               #pass image to the model
               prediction=Prediction.objects.last()
               img=ImageModel.objects.last()
       
               
               #print(now)
               print(img)
               
               url= img.imagefile
               top_p,top_class=image_pred(url)
               # out=dis[int(out)]
               print('----------------',url,'----------------')
               #print('-----disease is------- ',out,'----------')
               disease_map={0:'Tomato bacterial spot',1:'Tomato early blight',2:'Tomato late blight',3:'Tomato leaf mold',
               4:'Tomato septoira leaf spot',5:'Tomato spider mites',
               6:'Tomato target spot',7:'Tomato yellow leaf curl virus',
               8:'Tomato mossaic virus',
               9:'this is a healthy tomato',10:'Please upload a picture of a tomato leaf'}
               
        
               print(top_class)
               
               disease=None
               
               if top_class != 10:
                background=False
                disease=get_object_or_404(Disease,name=disease_map[top_class])
                new_prediction=Prediction()
                new_prediction.user=user
                new_prediction.image=img
                new_prediction.disease=disease
                new_prediction.save()
               else:
                background=True
                os.remove(os.path.join(settings.MEDIA_ROOT, str(url)))
                img.delete()
                   

               pestisides=Pestiside.objects.filter(disease=disease)
               context={'form':form,'image':img,'disease':disease,'pestisides':pestisides,'background':background}    
               return render(request,'diagnose/predict.html',context)

'''
class save_prediction(View):
   def get(self,request):
        user = User.objects.get(username=request.user)
        image=ImageModel.objects.last()
        disease=Disease.objects.get(name=image.result)
        new_prediction=Prediction()
        new_prediction.user=user
        new_prediction.disease=disease
        new_prediction.save()
        return render(request,'diagnose/predict.html')  
        '''  
    
class upload_profile(View):

    def post(self,request):
        user=request.user
        u_form=userdetailsForm(request.POST,instance=request.user)
        p_form=profileForm(request.POST,request.FILES,instance=request.user.profile)
    
        if u_form.is_valid() and p_form.is_valid():
            
               u_form.save()
               p_form.save()
            
               
               
               return redirect('diagnose:predictions')

    def get(self,request):
        
        u_form=userdetailsForm(instance=request.user)
        p_form=profileForm(instance=request.user.profile)
        return render(request,'diagnose/userprofile.html',{'u_form':u_form,'p_form':p_form})

class view_profile(View):
    def get(self,request):
        
        
        profile = Profile.objects.get_or_create(user=request.user)

        
        userprofile=profile.user
        prediction_info= Prediction.objects.filter(user=user)
        predictions=prediction_info.count()
        context={'user':userprofile,'predictions':predictions}
        return render(request,'diagnose/viewuserprofile.html',context)

class view_dashprofile(View):
    def get(self,request,*args,**kwargs):
        id_p = self.kwargs.get("id")
        
        profile=get_object_or_404(Profile,user__id=id_p)
        userprofile=profile.user
        prediction_info= Prediction.objects.filter(user=user)
        predictions=prediction_info.count()
        context={'user':userprofile,'predictions':predictions}
        return render(request,'diagnose/viewuserprofile.html',context)
     

#prediction list views
class predictions(View):


    def get(self,request):
        user = request.user
    
        
        prediction_info=Prediction.objects.filter(user=user).order_by('time').reverse()
        isadmin=False
        if user.username == 'admin':
            isadmin=True;
        else:
            isadmin=False;
     
        totals=prediction_info.count()
        diseases=[p.disease for p in prediction_info]
        image=[p.image for p in prediction_info]
        disease_list=set(diseases)
        pestisides=Pestiside.objects.all()
        suggestions=[Pestiside.objects.filter(disease__name=d.name) for d in diseases]
        #print(diseases)
        #print(suggestions)
        form = FilterForm() 
        context={'diseases': diseases,'form': form,'disease_list':disease_list,'images':image,'sugestions':suggestions,'predictions':prediction_info,'total':totals,'user':user,'admin':isadmin}
        return render(request,'diagnose/userbase.html',context)
    def post(self,request):
        if request.method=='POST':
            user = User.objects.get(username=request.user)
            profile=get_object_or_404(Profile,user=user)
            diseases=Disease.objects.all()
            form = FilterForm(request.POST) 
            if form.is_valid():
                print('sucessfull')
                selectedplant = form.cleaned_data['selected']
                if selectedplant == 'all':
                    predictions=Prediction.objects.filter(user=user)
                else:    
                    predictions = Prediction.objects.filter(user=user,disease__name=selectedplant)
                number=predictions.count()

                
            else:
                print('not')
                predictions = Prediction.objects.all().order_by('time')  
        else:
            predictions = Prediction.objects.all().order_by('time')    

        context =  {'predictions':predictions,'number':number,'profile':profile, 'form': form,'diseases':diseases}
        return render(request,'diagnose/userbase.html',context)

class prediction(View):
    template_name='diagnose/prediction.html'
    def get(self,request,*args,**kwargs):
        pk=self.kwargs.get("pk")
        prediction=get_object_or_404(Prediction,pk=pk)
        disease=prediction.disease
        if disease.name == 'this is a healthy tomato':
            healthy=True
        else:
            healthy=False    

        disease=prediction.disease
        pestisides=Pestiside.objects.filter(disease=disease.pk)

        image=prediction.image
        print(disease)
        print(pestisides)
        symptoms=disease.symptoms
        symptoms=symptoms.split(".")
          
        context={'prediction':prediction,'healthy':healthy,'disease':disease,'pestisides':pestisides,'image':image,"symptoms":symptoms}
        return render(request,self.template_name,context)
    



class delete_prediction(DeleteView):
    template_name='diagnose/predictions_delete.html'
    def get_object(self):
        id_=self.kwargs.get("id")
        return get_object_or_404(Prediction,id=id_)
    
    def get_success_url(self):
        return reverse('diagnose:predictions')
    
           
'''
def filter_predictions(request):
    user = User.objects.get(username=request.user)
    diseases=Disease.objects.all()
    form = FilterForm()
    sightings = []
    if request.POST:
        form = FilterForm(request.POST)
        if form.is_valid():
            print('sucessfull')
            selectedplant = form.cleaned_data['selectedplant']
            print(selectedplant)
            predictions = Prediction.objects.filter(disease=selectedplant)
            for p in predictions:
                print(p.time)
        else:
            print('not')
            predictions = Prediction.objects.all().order_by('time')  
    else:
        predictions = Prediction.objects.all().order_by('time')    

    context =  {'predictions':predictions, 'form': form,'diseases':diseases}
    return render(request,'diagnose/userbase.html',context)
'''

class review(View):
    template_name='diagnose/review.html'
    reviews= Review.objects.all().order_by('comment')
    
    def get(self,request):
        form= ReviewForm()
        self.user=None
        context={'form':form,'reviews':self.reviews,'user':self.user}
        return render(request,template_name,context)  
    def post(self,request):
        if request.method=='POST':
            user = User.objects.get(username=request.user)
            form= ReviewForm(request.POST)
            if form.is_valid():
                final_form=form(commit=False)
                final_form.save()
                comment=form.cleaned_data.get('review')

diagnose/templates/diagnose/admindash.html
{% extends 'diagnose/userbase.html' %}
{% load static %}
{% block content %}


{% endblock %}

diagnose/templates/diagnose/dashdisease.html
{% extends 'diagnose/userbase.html' %}
{% load static %}
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 150%;
}
.container1{
	display: flex;
	flex-direction: row;
	height: 100%;
width: 100%}
.container1 button a{
	
	text-decoration: none;
	font-weight: bold;
	color: #fff;
}
.main-flex{
	width: 100%;
	height: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
.main-flex{
	display: flex;
	flex-direction: row;
}
.container1 a{
	text-decoration:none;
	font-size: 1.8em;
	font-style: bold;
	font-color:#000;

}

</style>

  
 <section class="container1">
<!--dropdown list-->	
		<a href="{% url 'diagnose:dashpestisides' %}">Go to <strong>Pestisides</strong></a>			


</section> 
				
<div class="main-flex">
	
<section class='flex-column tables'>
	<div>
		<h3 class="table-tittle">Diseases</h3>
		<table>
			<tr>
				<th>Disease name</th>
				<th>number of predictions</th>
	
			</tr>
			
				{% for key, value in final_dict.items %} 
  {% if key != 'Please upload a picture of a tomato leaf' %}
  <tr>
  <td>{{key}}</td>
  <td>{{value}}</td>
  
</tr>

  {% endif %}
{% endfor %}
			

		</table>
	</div>
	


{% endblock %}

diagnose/templates/diagnose/dashpestisides.html
{% extends 'diagnose/userbase.html' %}
{% load static %}
{% block content %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 250%;
}
.container1{
	display: flex;
	flex-direction: row;
	height: 100%;
width: 100%}
.container1 button a{
	
	text-decoration: none;
	font-weight: bold;
	color: #fff;
}
}


td, th {
  border: 2px solid #dddddd;
  text-align: left;
  padding: 18px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
.main-flex{
	display: flex;
	flex-direction: row;
}
.container1 button{
		background: green;
	border-radius: 10px;
	height: 40px;
	margin:5px;
	left: 0;
	margin-left:860px;
}
.container1 a{
	text-decoration:none;
	font-size: 1.8em;
	font-style: bold;
	font-color:#000;

}
</style>

  
  
	<section class="container1">
<!--dropdown list-->	
		<a href="{% url 'diagnose:dashdiseases' %}">Go to <strong>Diseases</strong></a>			
<button><a href="{% url 'diagnose:add_pestiside' %}">+ Add pestiside</a></button>

</section>					
				
<div class="main-flex">
	
<section class='flex-column tables'>
	<div>
		<h2 class="table-tittle">Pestisides</h2>
		
		<table>
			<tr>
				<th>pestiside name</th>
				<th></th>

			</tr>
			{% for p in pestisides %}
			<tr>
				<td>{{p.name}}</td>
				{{p.disease_name.all}}
				{% for d in p.disease_name.all %}
				 
				<td>{{d}}a</td>
	
			   
				{% endfor %}

			 
				<td><button type="button"><a href="{% url 'diagnose:pestiside_details' p.id %}">view</a></button><button type="button"><a href="{% url 'diagnose:update_pestiside' p.id %}">Edit</a></button><button type="button"><a href="{% url 'diagnose:delete_pestiside' p.id %}">Delete</a></button></td>
			</tr>

{% endfor %}

		</table>
	</div></section>
	<div>
		<h3 class="table-tittle"></h3>
	</div>
	
</section>
</div>


{% endblock %}

diagnose/templates/diagnose/farms.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/userbase.css' %}">
</head>
<body>
	<main>
		<div class="header">
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">logout</a></li>
				<li><a href="#">my predictions</a></li>
				<li><a href="#">my farms </a></li>
			</ul>
		</div>
		<div class="container">
			<div class="flex-item sidepane side">
          
				
			</div>
			<div class="flex-item  main">
				<div>
					<h1 class="content-title">my farms</h1>
				</br>
					<button><a href="#">+ add farm</a></button>
				</div>
				<!--cards-->
				<div class="card">
					<img src="">
					<div class="content">
						<h2>farm name</h2>
						<p>size</p>
						<h3>number of predictions</h3>
					</div>	
				</div>
			</div>
			
			
		</div>
	</main>
</body>
</html>

diagnose/templates/diagnose/filter.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for p in predictions %}
p
{% endfor %}
</body>
</html>

diagnose/templates/diagnose/pestiside.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/userbase.css' %}">
</head>
<body>
	<main>
		<div class="header">
			<ul>
				<li><a href="{% url 'accounts:home' %}">Home</a></li>
						<li><a href="{% url 'diagnose:upload' %}">Diagnose</a></li>
						<li><a href="{% url 'diagnose:predictions' %}">My predictions</a></li>
						<li><a href="{% url 'accounts:logout' %}">logout</a></li>
			
			</ul>
		</div>
		<div class="container">
			
			<div class="flex-item  top">
				<div>
					<h1 class="content-title">pesticide:</h1>
				
				</div>
			</div>

				<!--cards-->
				<div class="flex-item main-content pestiside">
					
						<div class=" flex-row">
						<div><img src="{{ MEDIA_URL }}{{ pestiside.imagefile.url }}" height="460px" width="360px">
						</div>
						<div class="info"><h2>{{pestiside.name}}</h2>
                             <h2>Averrage Price : {{pestiside.price}}</h2>
                            <p class="directions"><h2>DIRECTIONS FOR USE:</h2>{{pestiside.directions}}</p>

						</div>
						</div>
				
					<div >
						
					</div>
					
					


				</div>

	

</body>
</html>

<style type="text/css">
	body{
  padding:50px;
}
.panel-heading{
  font-size:22px;
  font-weight:bold;
}
.panel-body b{
  font-size:20px;
}
.panel-body p{
  font-size:18px;
  padding-left:12px;
}
</style>

diagnose/templates/diagnose/predict.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/userbase.css' %}">
</head>
<body>
	<main>
		<div class="header">
			<ul>
				<li><a href="{% url 'accounts:home' %}">Home</a></li>
						<li><a href="{% url 'diagnose:predictions' %}">My predictions</a></li>
						<li><a href="{% url 'accounts:logout' %}">logout</a></li>
			</ul>
		</div>
		<div class="container">
			
			<div class="flex-item  top">
				<div>
					<h1 class="content-title">predict</h1>
				
				</div>
			</div>

				<!--cards-->
				<div class="flex-item main-content predict">
					{% if background %}
					<h3>sorry your image might be a background.Please upload an image of a tomato leaf
					 </h3>
					{% endif %}

                     {% if not disease %}
					<div>
					<h2>Please upload an image of a tomato leaf</h2>
						<div class="box">
                        
						
						<form method="POST" enctype="multipart/form-data">
							   	  	{% csrf_token %}
					
   	  	{{form.as_p}}
   	  	<img src="#">
   	  	<button type="submit"><strong>Diagnose</strong></button>
   	  </form>

						
					</div>
					
					
					</div>

					{% else %}
						<div class="box-results">
			
					
					  
							<form method="POST" enctype="multipart/form-data">
							<img src='{{ image.imagefile.url }}' width="150px" height="200px">
						</form>

						<h2>Results</h2>
						<ul>
							
							<li><strong>Disease:{{disease.name}}</strong></li>
							
							{% for p in pestisides %}
							 <li><a href="{% url 'diagnose:pestiside' pk=p.pk di=disease.pk %}"><img src="{{ MEDIA_URL }}{{ p.imagefile.url }}" height="100px" width="100px"></a></li>
										
											<li><h2>Suggested pesticide: </h2><a href="{% url 'diagnose:pestiside' pk=p.pk di=disease.pk %}">{{p.name}}</a></li>
							{% endfor %}
							<div class="btn">
							<ul>
							<li><button><a class="buttons" href="{% url 'diagnose:upload' %}" ><strong>make another prediction </strong></a></button>
							<button><a class="buttons"href="{% url 'diagnose:predictions'  %}"><strong>view your predictions</strong></a></button></li></ul>
						</div>
							
						
						</ul>
						
					  
					</div>

					{% endif %}
					

				</div>

				
				
				
			</div>
			
			
		</div>
	</main>
</body>
</html>

diagnose/templates/diagnose/prediction.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/userbase.css' %}">
</head>
<body>
	<main>
		<div class="header">
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="{% url 'accounts:logout' %}">logout</a></li>
				<li><a href="{% url 'diagnose:predictions' %}">my predictions</a></li>
			
			</ul>
		</div>
		<div class="container">
		
			<div class="flex-item  top">
				<div>
					<h1 class="content-title">prediction:</h1>
				
				</div>
			</div>

				<!--cards-->
				<div class="flex-item main-content pestiside">

					
						<div class=" flex-row">
							
						<div><img src='{{ image.imagefile.url }}' width="250px" height="300px"></div>
						<div class="results"><h2>Results</h2>
							<ul>
										<li><strong>Disease: </strong><strong>{{disease.name}}</strong></li>
										<li><strong>Description </strong>{{disease.description}}</li>
										{% if healthy %}
										<P></P>
										{% else %}
										<h2><strong>Symptoms</strong></h2>
										{% for s in symptoms %}
										<li>{{s}}</li>
										{% endfor %}
										<h2><strong>Suggested pesticide:</strong></h2>
										{% for p in pestisides %}
										    <li><a href="{% url 'diagnose:pestiside' pk=p.pk di=disease.pk %}"><img src="{{ MEDIA_URL }}{{ p.imagefile.url }}" height="100px" width="100px"></a></li>
										
											<li><a href="{% url 'diagnose:pestiside' pk=p.pk di=disease.pk %}">{{p.name}}</a></li>
											
										{% endfor %}

										{% endif %}
										
										
										


									</ul>
								
                            
						</div>
						<div class="suggesions">
							<div>
								<img src="">
								<h2></h2>
							</div>
							
						</div>
						</div>
						
				
					<div >
						
					</div>
					
					


				</div>

				
				
				
			</div>
			
			
		</div>
	</main>
</body>
</html>

diagnose/templates/diagnose/review.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="" method="Post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="coment">
</form>

{% for r in reviews %}
{% if r.comment %}
 <div class="box">
 	<h2></h2>
 	
 	<p>Author: {{r.author}} {{r.comment}}<p>
 		{% if r.author == user.username %}
 		<button>delete</button>
         <button>edit</button>
 		{% endif %}

 </div>

 {% endif %}

{% endfor %}
 
</body>
<style type="text/css">
	.box{
		border: 1px solid #333;
	}
</style>
</html>

diagnose/templates/diagnose/viewuserprofile.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div class="">
  <h1 class="well">Shamari Ishmael</h1>
  <br />
  <br />

  <div>
    <img class="profile" src="#"
      alt="" />


    <div class="list-group col-md-6 pull-right pad">
      <p class="list-group-item highlight">Username<span class="pull-right">{{user.username}}</span></p>
      <p class="list-group-item highlight">First Name<span class="pull-right">{{user.username}}</span></p>
      <p class="list-group-item highlight">Last Name<span class="pull-right">{{user.username}}</span></p>
      <p class="list-group-item highlight">email<span class="pull-right">{{user.email}}</span></p>
      <p class="list-group-item highlight">Total predictions <span class="pull-right">{{predictions}}</span></p>
     
      
      <br />
      
      
      <div class="pull-right">
        <button class="btn btn-success btn-md" onclick="{% url 'diagnose:profile' %}"> Edit</button>
        <button class="btn btn-danger btn-md" onclick="{% url 'password_reset' %}">Reset Password</button>
      </div>
    </div>
  </div>
  <br/>


</div>
<style type="text/css">
	.profile
{
  margin-left:50px;
  border-radius: 100%;
}

.highlight:hover
{
  background-color: #f2f2f2;
}

hr
{
  width: 100px;
}

.pad
{
  padding-right:50px;
}
</style>
</body>
</html>