Tomadoc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    
    path('diagnose/',include('diagnose.urls')),
   # path('accounts', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'), name='password_reset_complete'), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views

from . import views
app_name='accounts'
urlpatterns = [
    path('',views.home,name="home"),
    path('accounts/login/',views.login_view,name='logIn'),
    path('accounts/register/',views.register_view,name='register'),
   path('accounts/logout/',views.logout_view,name='logout'),

   # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registrations/password_reset_form.html'), name='password_reset'),
   # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registrations/password_reset_done.html'), name='password_reset_done'),
    #path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    #path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registrations/password_reset_complete.html'), name='password_reset_complete'),      
    ]

diagnose/urls.py
from django.urls import path,include
from . import views
app_name='diagnose'
urlpatterns = [
    path('upload/',views.upload.as_view(),name="upload"),
    path('predictions/',views.predictions.as_view(),name="predictions"),
    path('predictions/<int:id>/',views.delete_prediction.as_view(),name="delete_prediction"),
     path('pestidide/<int:id>/',views.delete_review.as_view(),name="delete_review"),
    #path('predictions/filtered',views.filter_predictions,name="filter_predictions"),
    path('prediction/<int:pk>/',views.prediction.as_view(),name="prediction"),
    path('pestiside/<int:pk>/<int:di>',views.Pestisides.as_view(),name="pestiside"),
    path('pestiside/review/<int:pk>/<int:di>',views.CommentView.as_view(),name="comment"),
    path('review/',views.review.as_view(),name="review"),
     path('profile/',views.upload_profile.as_view(),name="profile"),
     path('viewprofile/',views.view_profile.as_view(),name="view_profile"),
     path('dashboard/viewprofile/<int:id>/',views.view_dashprofile.as_view(),name="view_dashprofile"),
      path('dashboard/users',views.View_usersa.as_view(),name="dashusersa"),
      path('dashboard/diseases',views.View_Diseases.as_view(),name="dashdiseases"),
      path('dashboard/pestisides',views.View_Pestisides.as_view(),name="dashpestisides"),
      path('add_pestiside/',views.AddPestiside.as_view(),name="add_pestiside"),
       path('pestiside/<int:id>/',views.delete_pestiside.as_view(),name="delete_pestiside"),
       path('pestiside_update/<int:id>/',views.update_pestiside.as_view(),name="update_pestiside"),
       path('pestiside_details/<int:id>/',views.pestiside_details.as_view(),name="pestiside_details"),
       path('edit/<int:id>/',views.editDisease.as_view(),name="editDisease"),
   ]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    """docstring for ClassName"""
    phone_number = models.CharField(max_length=10)
   
    

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate,get_user_model
from .models import *

User = get_user_model()

class UserLoginForm(forms.Form):
    """docstring for UserLoginForm"""
    username= forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput)
    

    def clean(self, *args, **kwargs):
        username=self.cleaned_data.get('username')
        password=self.cleaned_data.get('password')
        
        if username and password:
            user = authenticate(username=username,password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            
            if not user.check_password(password):
                raise forms.ValidationError("Incorect password")
            
            if not user.is_active:
                raise forms.ValidationError("This user is not active")
        
        return  super(UserLoginForm,self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    """docstring for UserRegisterForm"""
    email = forms.EmailField(label='Email Address')
    phone_number = forms.CharField(label='Phone number')
    password = forms.CharField(widget=forms.PasswordInput)
   
    class Meta:
        model =User
        fields= ['first_name','last_name','username','email','password','phone_number']
        
    def clean(self, *args, **kwargs):

        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        

        """if password != confirm_password:
            raise forms.ValidationError("passwords must match")
        if len(password)<8:
            raise forms.ValidationError("passwords must be more than 8")
            """
        
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("this email is already been used")

        return super(UserRegisterForm, self).clean(*args, **kwargs)

accounts/views.py
from django.shortcuts import render,redirect

from django.contrib.auth import authenticate,get_user_model,login,logout
from .forms import UserLoginForm,UserRegisterForm
from diagnose.models import *
from django.shortcuts import get_object_or_404

# Create your views here.

def home(request):
    user = request.user

        
    context={'user':user}
           
    return render(request,'accounts/Home.html',context)

def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data.get('username')
        password=form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)

        if next:
            return redirect(next)
        return redirect('accounts:home')

    context={'form':form}
    return render(request, 'accounts/login.html', context)    

def register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user= authenticate(username=user.username, password=password)
        login(request, new_user)

        if next:
            return redirect(next)
        return redirect('accounts:logIn')

    context={'form':form}
    return render(request, 'accounts/register.html', context)  

def logout_view(request):
    logout(request)
    return redirect('/')

accounts/templates/accounts/Home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/main.css' %}">
</head>
<body>

		
	
	<div class="container">
			<div class="section">
				<div class="header">
					{% if user.is_authenticated %}
					 <ul>
						<li><a href="{% url 'accounts:home' %}">Home</a></li>
						<li><a href="{% url 'diagnose:predictions' %}">my predictions</a></li>
						<li><a href="{% url 'diagnose:upload' %}">Diagnose</a></li>
						<li><a href="{% url 'accounts:logout' %}">logout</a></li>
						<li><a href="#about">About us</a></li>
						<li><a href="#contact">contact us </a></li>
						
						

						{% if profile %}
				<!---<li>
  <a href="{% url 'diagnose:view_profile' %}"><img src="{{ profile.imagefile.url }}" width="30px" height="30px"></a>--->
  
  </a></li> 
  <li><a href="{% url 'diagnose:view_profile' %}"><h2>{{user.username}}</h2></a></li>{% endif %}

					</ul>
					{% else %}
					  <ul>
						<li><a href="#">Home</a></li>
						<li><a href="{% url 'accounts:logIn' %}">login</a></li>
						<li><a href="{% url 'accounts:register' %}">SignUp</a></li>
						
						<li><a href="#about">About us</a></li>
						<li><a href="#contact">contact us </a></li>
					</ul>
					{% endif %}
					
				</div>
					<div class="content">
						{% if user.is_authenticated %}
						<h1>TOMADOC</h1>	
						<h2>Welcome {{user.username}}</h2>
						    {% if profile.image %}
							<img  class="profile" src='{{ profile.imagefile.url }}' height="100px" width="150px">
							{% endif %}
						
						
						{% endif %}
						<h2>Welcome to <strong>Tomadoc</strong></h2>
						<h2><strong>Diagnose your tomato plant.</strong></h2>
						<a href="{% url 'diagnose:upload' %}"><button><strong>DIAGNOSE</stong></button></a>
					</div>
	       </div>

<div  class="section info"></div>

          <!--<div  class="section info">
          <div class="icon-infos">
          		<h1><strong>HOW IT WORKS</strong></h1>
          	</div>
          	<div class="icons">
          	<div class="icon-info">
          		<img src="{% static 'IMAGES/icon1.png' %}" height="150px" width="150px">
          		<p><strong>Take a Picture</strong></p>
          	</div>
          	<div class="icon-info" >
          		<img src="{% static 'IMAGES/hebal.png' %}" height="150px" width="150px">
          		<p><strong>Diagnose and treat</strong></p>
          	</div>
          	<div class="icon-info">
          		<img src="{% static 'IMAGES/tomato.png'%}" height="150px" width="150px">
          		<p><strong>Get a healty tomato</strong></p>
          	</div>
          </div>
          </div>-->
			
	       <div class="section about" id="about">
		       	<div class="image">
		       		<img src="{% static 'IMAGES/index.gif'%}" >
		       	</div>

		       	<div class="info">
			       		<h1>About us</h1>
			       	<p>Tomadoc is a web app that helps tomato farmers to diagnose diseases .By uploading a photo .Get the result and suggested treatment.Follow the treatment and get better results.The user can leave a comment on the pestiside used.  </p>
			       	<p>Our mission is to help farmers to grow healthy tomatoes.</p>
		       	</div>
	       	</div>


	       <div class="section contact" id="contact">
		       	
		       	
			       <div class="cont">
	<div class="row">
			<h1>contact us</h1>
	</div>
	<div class="row">
			<h4 style="text-align:center">We'd love to hear from you!</h4>
	</div>
	<div class="row input-container">
			<h2>Email: tomadoc@gmail.com</h2>
			<h2>number: +254792792372</h2>
			</div>
	</div>
</div>

		       
		       	

	       	</div>

	</div>

		<style type="text/css">
			
		</style>
	

</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		body{
			margin: 0;
			padding: 0;
		}
		body:before{
			content:'';
			position: fixed;
			height: 100vw;
			width: 100vw;
			background-image:  url("https://netstorage-tuko.akamaized.net/images/503d7b8f74917dab.jpg?imwidth=1200&impolicy=default-amp");
			background-position: center center;
			background-repeat: no-repeat;
			background-attachment: fixed;
			background-size: cover;
			filter: blur(8px);
           -webkit-filter: blur(8px);


		}
       .container{
       	position: absolute;
       	display: table;
        left: 30%;
        top: 20%;
       	width: 300px;
       	
       	background:rgb(0,0,0,0.5);
       	padding:50px 60px; 
       	 
       }
       .container h2{
       	margin: 0;
       	padding: 0 0 20px;
       	color: #fff;
       	text-align: center;
       }

       form{

       	display: flex;
       	flex-direction: column;
       	align-items: center;
       	justify-content: center;
       
       }

       input{
        border: 1px solid #424242;
       	margin: 10px;

       }
       input[type=submit]{
       	height: 30px;
       	color: #fff;
       	background:red;
       	cursor: pointer;
       	border-radius: 25px;
       	border: none;
       	outline: none;
       	margin-top: 15%; 

       }
	</style>
</head>
<body>

	<div class="container">
		<!--<img src="https://netstorage-tuko.akamaized.net/images/503d7b8f74917dab.jpg?imwidth=1200&impolicy=default-amp">-->
   {% block content %}
		<h2 class="form-title">LOGIN</h2>

		<form method="POST">
			{% csrf_token %}
			{{form}}
			<input type="submit" name="submit" class="btn" value="LOGIN">
      <a href="{% url 'password_reset' %}">forgot password</a>
      <a href="{% url 'accounts:register' %}">create acount</a>
		</form>
    {% endblock %}
		
	</div>
	
</body>
</html>

accounts/templates/accounts/register.html
{% extends "accounts/login.html" %}
{% block content %}
		<h2 class="form-title"><strong>SIGN UP</strong></h2>

		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" name="submit" class="btn" value="SIGN UP">
      
      <a href="{% url 'accounts:logIn' %}" style="color: #fff;"><strong>Already have an account?</strong></a>
		</form>
    {% endblock %}